name:                lam
version:             0.1.0.0
github:              "BillyBadBoy/lambda"
license:             BSD3
author:              "William Morgan"
maintainer:          "william.morgan@hotmail.co.uk"
copyright:           "2018 William Morgan"

extra-source-files:
- README.md

synopsis:            Untyped lambda calculus experiments

description:         Please see the README on Github at <https://github.com/BillyBadBoy/lambda#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lam-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - lam

tests:
  lam-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - HUnit
    - tasty
    - tasty-hunit
    - lam
